<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.lengye</groupId>
    <artifactId>yy-data</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>yy-data-admin</module>
        <module>yy-data-facade</module>
    </modules>
    <version>1.0-SNAPSHOT</version>
    <name>yy-data</name>
    <url>http://maven.apache.org</url>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-boot.version>3.0.5</spring-boot.version>
        <common.version>1.0-SNAPSHOT</common.version>
        <fastjson.version>2.0.20</fastjson.version>
        <lombok.version>1.18.34</lombok.version>
        <job.version>2.3.0</job.version>
        <liquibase-core.version>4.2.2</liquibase-core.version>
        <nacos-client.version>2.0.4</nacos-client.version>
        <mockito-core.version>3.9.0</mockito-core.version>
        <junit.version>4.13.2</junit.version>
        <maven-deploy-plugin.version>2.7</maven-deploy-plugin.version>
        <maven-compiler-plugin.version>3.1</maven-compiler-plugin.version>
        <io.micrometer.version>1.5.14</io.micrometer.version>
        <knife4j-openapi3-jakarta-spring-boot-starter.version>4.1.0
        </knife4j-openapi3-jakarta-spring-boot-starter.version>
        <mybatis-plus-boot-starter.version>3.5.3.1</mybatis-plus-boot-starter.version>
        <yy-data-facade.version>1.0-SNAPSHOT</yy-data-facade.version>
    </properties>

    <!--需要引入更为强悍的能力boot最新版本3.0.5-->
    <dependencyManagement>
        <dependencies>
            <!--boot版本3.0.x起，JDK最低版本要求：JDK17-->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
                <version>${knife4j-openapi3-jakarta-spring-boot-starter.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>${mybatis-plus-boot-starter.version}</version>
            </dependency>


            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>${fastjson.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-actuator</artifactId>
                <version>3.0.5</version>
            </dependency>

            <!-- prometheus -->
            <dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-registry-prometheus</artifactId>
                <version>${io.micrometer.version}</version>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>

            <dependency>
                <groupId>com.lengye</groupId>
                <artifactId>yy-data-facade</artifactId>
                <version>${yy-data-facade.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.8</version>
                <executions>
                    <execution>
                        <id>default-prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>default-report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                        <configuration>
                            <includes>
                                **/controller/**,
                                **/service/impl/**
                            </includes>
                            <outputDirectory>target/jacoco-report</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
